version: '3.8'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: danmal735/taski_backend
    env_file: .env
    volumes:
      - static:/backend_static
  frontend:
    image: danmal735/taski_frontend
    env_file: .env
    command: cp -r /app/build/. /staticfiles/
    volumes:
      - static:/staticfiles/
  gateway:
    image: danmal735/taski_gateway
    env_file: .env
    volumes:
      - static:/app/static/
    ports:
      - 8000:80